# Generated by Django 4.1.6 on 2023-02-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryitem',
            options={'verbose_name': 'Элемент категории', 'verbose_name_plural': 'Элементы категории'},
        ),
    ]
