# Generated by Django 4.1.6 on 2023-02-13 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'verbose_name': 'Ментор', 'verbose_name_plural': 'Менторы'},
        ),
    ]
