# Generated by Django 4.1.6 on 2023-02-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterField(
            model_name='application',
            name='service',
            field=models.CharField(choices=[('Ознакомительный урок', 'Ознакомительный урок'), ('Урок закрепления', 'Урок закрепления'), ('Урок практики', 'Урок практики')], max_length=69, verbose_name='Уроки'),
        ),
    ]
